### ISSUE TITLE
The example is completely non working

### ISSUE THREAD

**Issue by aligin** [jonniespratley/angular-bootcards#1]
Where dooes all these scrips?
```
<script src="/jquery/dist/jquery.js"></script>
<script src="/angular/angular.js"></script>
and so .....
```

**Comment by jonniespratley** [comment]
Where dooes all these scripts?

Please explain. I do know that I am still working on creating all of the logic behind the directives, as of right now, they are simply angular directives that produce the default markup as described on the Bootcards website. To run the development server, just do the following.


1. Checkout the develop branch `$ git checkout develop`
2. Update the develop branch `$ git pull origin develop`
3. Install dependencies `$ npm install`
4. Start the server `$ grunt serve`
5. Your browser should open up displaying the index.html page.
